Project2.class : Project2.java Buttons.class Canvas.class Data.class DesignElement.class ElementPanel.class FileIO.class FillPanel.class Palette.class SelectedPanel.class StrokePanel.class Design6.class Image.class Design8.class Kaleidoscope.class
	javac Project2.java

Canvas.class : Canvas.java
	javac Canvas.java

Data.class : Data.java
	javac Data.java

DesignElement.class : DesignElement.java
	javac DesignElement.java

FileIO.class : FileIO.java
	javac FileIO.java

Buttons.class : Buttons.java
	javac Buttons.java

ElementPanel.class : ElementPanel.java
	javac ElementPanel.java

FillPanel.class : FillPanel.java
	javac FillPanel.java

Palette.class : Palette.java
	javac Palette.java

SelectedPanel.class : SelectedPanel.java
	javac SelectedPanel.java

StrokePanel.class : StrokePanel.java
	javac StrokePanel.java

Design6.class : Design6.java
	javac Design6.java

Design8.class : Design8.java
	javac Design8.java

Kaleidoscope.class : Kaleidoscope.java	
	javac Kaleidoscope.java

Image.class : Image.java
	javac Image.java

clean :
	rm *.class

submit : Buttons.java Canvas.java Data.java DesignElement.java ElementPanel.java Project2.java FileIO.java FillPanel.java Palette.java SelectedPanel.java StrokePanel.java Design6.java Design8.java Kaleidoscope.java Image.java makefile 
	rm -rf reynaP2
	mkdir reynaP2
	cp Buttons.java reynaP2
	cp Canvas.java reynaP2
	cp Data.java reynaP2
	cp Design6.java reynaP2
	cp DesignElement.java reynaP2
	cp ElementPanel.java reynaP2
	cp Project2.java reynaP2
	cp FileIO.java reynaP2
	cp FillPanel.java reynaP2
	cp Image.java reynaP2
	cp Palette.java reynaP2
	cp SelectedPanel.java reynaP2
	cp StrokePanel.java reynaP2
	cp makefile reynaP2

	tar cfvz reynaP2.tgz reynaP2
	cp reynaP2.tgz ~tiawatts/cs375drop

